name: print-name

on:
  push:
    branches:
      - main

jobs:
  print-name-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Added print-name
        run: echo "Added print-name"

